let dados = [
    {
      titulo: "GOTY 2003",
      ganhador: "Madden NFL 2004",
      descrição: "O GOTY de 2003: Madden NFL 2004. Um dos jogos de futebol americano mais populares da época.",
      link: "https://pt.wikipedia.org/wiki/Madden_NFL_2004"
    },
    {
      titulo: "GOTY 2004",
      ganhador: "Grand Theft Auto: San Andreas",
      descrição: "O GOTY de 2004: Grand Theft Auto: San Andreas. Um mundo aberto massivo, com uma história rica e diversas atividades.",
      link: "https://www.https://www.rockstargames.com/br/games/sanandreas.com/gta3"
    },
    {
      titulo: "GOTY 2005",
      ganhador: "Resident Evil 4",
      descrição: "O GOTY de 2005: Resident Evil 4. Um marco nos jogos de terror de sobrevivência, com uma jogabilidade inovadora e uma história intensa.",
      link: "https://www.residentevil.com/re4/pt-br/"
    },
    {
      titulo: "GOTY 2006",
      ganhador: "The Elder Scrolls IV: Oblivion",
      descrição: "O GOTY de 2006: The Elder Scrolls IV: Oblivion. Um RPG de mundo aberto épico, com uma história envolvente e infinitas possibilidades.",
      link: "https://www.elderscrolls.com/"
    },
    {
      titulo: "GOTY 2007",
      ganhador: "BioShock",
      descrição: "O GOTY de 2007: BioShock. Um FPS com elementos de RPG, ambientado em uma cidade subaquática distópica.",
      link: "https://pt.wikipedia.org/wiki/BioShock"
    },
    {
      titulo: "GOTY 2008",
      ganhador: "Grand Theft Auto IV",
      descrição: "O GOTY de 2008: Grand Theft Auto IV. Uma revolução no gênero sandbox, com uma história mais madura e um mundo mais realista.",
      link: "https://www.rockstargames.com/gtaiv"
    },
    {
      titulo: "GOTY 2009",
      ganhador: "Uncharted 2: Among Thieves",
      descrição: "O GOTY de 2009: Uncharted 2: Among Thieves. Uma aventura de ação com gráficos impressionantes e uma narrativa cinematográfica.",
      link: "https://www.playstation.com/en-us/games/uncharted-collection/"
    },
    {
      titulo: "GOTY 2010",
      ganhador: "Red Dead Redemption",
      descrição: "O GOTY de 2010: Red Dead Redemption. Um western de mundo aberto, com uma história envolvente e personagens memoráveis.",
      link: "https://www.rockstargames.com/reddeadredemption2/"
    },
    {
      titulo: "GOTY 2011",
      ganhador: "The Elder Scrolls V: Skyrim",
      descrição: "O GOTY de 2011: The Elder Scrolls V: Skyrim. Um RPG de mundo aberto épico, com liberdade quase ilimitada para explorar e personalizar o personagem.",
      link: "https://www.elderscrolls.com/"
    },
    {
      titulo: "GOTY 2012",
      ganhador: "The Walking Dead",
      descrição: "O GOTY de 2012: The Walking Dead. Uma aventura point-and-click baseada na série de quadrinhos, com escolhas que impactam a história.",
      link: "https://thewalkingdead.com/"
    },
    {
      titulo: "GOTY 2013",
      ganhador: "GTA V",
      descrição: "O GOTY de 2013: Grand Theft Auto V. Em 2013, o título de Jogo do Ano (GOTY) foi para Grand Theft Auto V, da Rockstar Games.",
      link: "https://www.rockstargames.com/br/gta-v"
    },
    {
      titulo: "GOTY 2014",
      ganhador: "Dragon Age: Inquisition",
      descrição: "O GOTY de 2014: Dragon Age: Inquisition. Um RPG épico da BioWare que conquistou os jogadores com seu mundo aberto e história envolvente.",
      link: "https://www.ea.com/pt-br/games/dragon-age"
    },
    {
      titulo: "GOTY 2015",
      ganhador: "The Witcher 3: Wild Hunt",
      descrição: "O GOTY de 2015: The Witcher 3: Wild Hunt. Um RPG de mundo aberto aclamado pela crítica e pelos jogadores, com uma narrativa rica e um mundo vasto para explorar.",
      link: "https://www.thewitcher.com/"
    },
    {
      titulo: "GOTY 2016",
      ganhador: "Overwatch",
      descrição: "O GOTY de 2016: Overwatch. Um jogo de tiro em primeira pessoa multiplayer que revolucionou o gênero com seus personagens carismáticos e jogabilidade frenética.",
      link: "https://playoverwatch.com/"
    },
    {
      titulo: "GOTY 2017",
      ganhador: "The Legend of Zelda: Breath of the Wild",
      descrição: "O GOTY de 2017: The Legend of Zelda: Breath of the Wild. Uma reinvenção épica da série Zelda, com um mundo aberto imenso e liberdade de exploração.",
      link: "https://www.zelda.com/"
    },
    {
      titulo: "GOTY 2018",
      ganhador: "God of War",
      descrição: "O GOTY de 2018: God of War. Um reinício da franquia God of War, com uma narrativa emocionante e uma jogabilidade visceral.",
      link: "https://www.playstation.com/en-us/games/god-of-war/"
    },
    {
      titulo: "GOTY 2019",
      ganhador: "Sekiro: Shadows Die Twice",
      descrição: "O GOTY de 2019: Sekiro: Shadows Die Twice. Um jogo de ação e aventura desafiador, desenvolvido pela FromSoftware, conhecido por sua jogabilidade precisa e mundo sombrio.",
      link: "https://www.fromsoftware.jp/sekiro/"
    },
    {
      titulo: "GOTY 2020",
      ganhador: "The Last of Us Part II",
      descrição: "O GOTY de 2020: The Last of Us Part II. Uma sequência emocionalmente intensa que continua a história de Ellie e Joel, com uma narrativa complexa e jogabilidade refinada.",
      link: "https://www.playstation.com/en-us/games/the-last-of-us-2/"
    },
    {
      titulo: "GOTY 2021",
      ganhador: "It Takes Two",
      descrição: "O GOTY de 2021: It Takes Two. Um jogo cooperativo focado na narrativa, que celebra o poder dos relacionamentos e oferece uma experiência única para jogadores em dupla.",
      link: "https://www.ea.com/pt-br/games/it-takes-two"
    },
    {
      titulo: "GOTY 2022",
      ganhador: "Elden Ring",
      descrição: "O GOTY de 2022: Elden Ring. Um RPG de mundo aberto desenvolvido pela FromSoftware, que oferece uma experiência desafiadora e rica em exploração.",
      link: "https://www.eldenring.com/"
    },
    {
      titulo: "GOTY 2023",
      ganhador: "Baldur's Gate 3",
      descrição: "Baldur's Gate 3 conquistou o título de GOTY 2023 com sua narrativa envolvente, jogabilidade profunda e mundo rico em detalhes.",
      link: "https://www.baldursgate3.com/"
    }
  ];
  
  
  let anos = [
    {
        Ano: "2003",
        JogodoAno: "Madden NFL 2004",
        MelhorDireção: "Spike VGA 2003 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "Star Wars: Knights of the Old Republic",
        MelhorAtuação: "Spike VGA 2003 não possui uma categoria específica para Melhor Atuação",
        MelhorTrilhaSonora: "Tony Hawk’s Underground",
        MelhorDesigndeaudio: "Need for Speed: Underground",
        MelhorDesigndeJogo: "Spike VGA 2003 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "Spike VGA 2003 não possui uma categoria específica para Melhor Jogo Independente",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2003 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Madden NFL 2004, Star Wars: Knights of the Old Republic, Tony Hawk’s Underground, Need for Speed: Underground, 2003"
    },
    {
        Ano: "2004",
        JogodoAno: "Grand Theft Auto: San Andreas",
        MelhorDireção: "Spike VGA 2004 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "Half-Life 2",
        MelhorAtuação: "Samuel L. Jackson como Officer Frank Tenpenny em Grand Theft Auto: San Andreas",
        MelhorTrilhaSonora: "Halo 2",
        MelhorDesigndeaudio: "Halo 2",
        MelhorDesigndeJogo: "Spike VGA 2004 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "Spike VGA 2004 não possui uma categoria específica para Melhor Jogo Independente",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2004 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Grand Theft Auto: San Andreas, Half-Life 2, Halo 2, Samuel L. Jackson, 2004",
    },
    {
        Ano: "2005",
        JogodoAno: "Resident Evil 4",
        MelhorDireção: "Spike VGA 2005 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "God of War",
        MelhorAtuação: "Jack Black como Eddie Riggs em Brutal Legend",
        MelhorTrilhaSonora: "Guitar Hero",
        MelhorDesigndeaudio: "Resident Evil 4",
        MelhorDesigndeJogo: "Spike VGA 2005 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "Spike VGA 2005 não possui uma categoria específica para Melhor Jogo Independente",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2005 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Resident Evil 4, God of War, Guitar Hero, Jack Black, 2005",
    },
    {
        Ano: "2006",
        JogodoAno: "The Elder Scrolls IV: Oblivion",
        MelhorDireção: "Spike VGA 2006 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "The Elder Scrolls IV: Oblivion",
        MelhorAtuação: "Patrick Stewart como Uriel Septim VII em The Elder Scrolls IV: Oblivion",
        MelhorTrilhaSonora: "The Elder Scrolls IV: Oblivion",
        MelhorDesigndeaudio: "Call of Duty 3",
        MelhorDesigndeJogo: "Spike VGA 2006 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "Spike VGA 2006 não possui uma categoria específica para Melhor Jogo Independente",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2006 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "The Elder Scrolls IV: Oblivion, Call of Duty 3, Patrick Stewart, 2006",
    },
    {
        Ano: "2007",
        JogodoAno: "BioShock",
        MelhorDireção: "Spike VGA 2007 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "BioShock",
        MelhorAtuação: "Spike VGA 2007 não possui uma categoria específica para Melhor Atuação",
        MelhorTrilhaSonora: "Halo 3",
        MelhorDesigndeaudio: "Call of Duty 4: Modern Warfare",
        MelhorDesigndeJogo: "Spike VGA 2007 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "Everyday Shooter",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2007 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "BioShock, Halo 3, Call of Duty 4: Modern Warfare, Everyday Shooter, 2007",
    },
    {
        Ano: "2008",
        JogodoAno: "Grand Theft Auto IV",
        MelhorDireção: "Spike VGA 2008 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "Grand Theft Auto IV",
        MelhorAtuação: "Michael Hollick como Niko Bellic em Grand Theft Auto IV",
        MelhorTrilhaSonora: "Rock Band 2",
        MelhorDesigndeaudio: "Dead Space",
        MelhorDesigndeJogo: "Spike VGA 2008 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "World of Goo",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2008 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Grand Theft Auto IV, Dead Space, World of Goo, Michael Hollick, 2008",
    },
    {
        Ano: "2009",
        JogodoAno: "Uncharted 2: Among Thieves",
        MelhorDireção: "Spike VGA 2009 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "Uncharted 2: Among Thieves",
        MelhorAtuação: "Hugh Jackman como Wolverine em X-Men Origins: Wolverine",
        MelhorTrilhaSonora: "DJ Hero",
        MelhorDesigndeaudio: "Call of Duty: Modern Warfare 2",
        MelhorDesigndeJogo: "Spike VGA 2009 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "Flower",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2009 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Uncharted 2: Among Thieves, DJ Hero, Call of Duty: Modern Warfare 2, Flower, 2009",
    },
    {
        Ano: "2010",
        JogodoAno: "Red Dead Redemption",
        MelhorDireção: "Spike VGA 2010 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "Mass Effect 2",
        MelhorAtuação: "Neil Patrick Harris como Peter Parker / Spider-Man em Spider-Man: Shattered Dimensions",
        MelhorTrilhaSonora: "DJ Hero 2",
        MelhorDesigndeaudio: "Red Dead Redemption",
        MelhorDesigndeJogo: "Spike VGA 2010 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "Limbo",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2010 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Red Dead Redemption, DJ Hero 2, Mass Effect 2, Limbo, 2010",
    },
    {
        Ano: "2011",
        JogodoAno: "The Elder Scrolls V: Skyrim",
        MelhorDireção: "Spike VGA 2011 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "Portal 2",
        MelhorAtuação: "Stephen Merchant como Wheatley em Portal 2",
        MelhorTrilhaSonora: "Bastion",
        MelhorDesigndeaudio: "Batman: Arkham City",
        MelhorDesigndeJogo: "Spike VGA 2011 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "Minecraft",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2011 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "The Elder Scrolls V: Skyrim, Portal 2, Bastion, Minecraft, Stephen Merchant, 2011",
    },
    {
        Ano: "2012",
        JogodoAno: "The Walking Dead: The Game",
        MelhorDireção: "Spike VGA 2012 não possui uma categoria específica para Melhor Direção",
        MelhorNarrativa: "The Walking Dead: The Game",
        MelhorAtuação: "Melissa Hutchison como Clementine em The Walking Dead: The Game",
        MelhorTrilhaSonora: "Journey",
        MelhorDesigndeaudio: "Halo 4",
        MelhorDesigndeJogo: "Spike VGA 2012 não possui uma categoria específica para Melhor Design de Jogo",
        MelhorJogoIndependente: "Journey",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2012 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "The Walking Dead: The Game, Journey, Halo 4, Melissa Hutchison, 2012",
    },
    {
        Ano: "2013",
        JogodoAno: "The Last of Us",
        MelhorDireção: "The Last of Us",
        MelhorNarrativa: "The Last of Us",
        MelhorAtuação: "Troy Baker como Joel em The Last of Us",
        MelhorTrilhaSonora: "The Last of Us",
        MelhorDesigndeaudio: "The Last of Us",
        MelhorDesigndeJogo: "The Last of Us",
        MelhorJogoIndependente: "Gone Home",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2013 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "The Last of Us, Gone Home, Troy Baker, 2013",
    },
    {
        Ano: "2014",
        JogodoAno: "Dragon Age: Inquisition",
        MelhorDireção: "Dragon Age: Inquisition",
        MelhorNarrativa: "Dragon Age: Inquisition",
        MelhorAtuação: "Troy Baker como Dorian Pavus em Dragon Age: Inquisition",
        MelhorTrilhaSonora: "Destiny",
        MelhorDesigndeaudio: "Destiny",
        MelhorDesigndeJogo: "Dragon Age: Inquisition",
        MelhorJogoIndependente: "Hades",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2014 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Dragon Age: Inquisition, Destiny, Hades, Troy Baker, 2014",
    },
    {
        Ano: "2015",
        JogodoAno: "The Witcher 3: Wild Hunt",
        MelhorDireção: "The Witcher 3: Wild Hunt",
        MelhorNarrativa: "The Witcher 3: Wild Hunt",
        MelhorAtuação: "Doug Cockle como Geralt de Rivia em The Witcher 3: Wild Hunt",
        MelhorTrilhaSonora: "The Witcher 3: Wild Hunt",
        MelhorDesigndeaudio: "The Witcher 3: Wild Hunt",
        MelhorDesigndeJogo: "The Witcher 3: Wild Hunt",
        MelhorJogoIndependente: "Rocket League",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2015 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "The Witcher 3: Wild Hunt, Rocket League, Doug Cockle, 2015",
    },
    {
        Ano: "2016",
        JogodoAno: "Overwatch",
        MelhorDireção: "Overwatch",
        MelhorNarrativa: "Uncharted 4: A Thief's End",
        MelhorAtuação: "Nolan North como Nathan Drake em Uncharted 4: A Thief's End",
        MelhorTrilhaSonora: "DOOM",
        MelhorDesigndeaudio: "DOOM",
        MelhorDesigndeJogo: "Overwatch",
        MelhorJogoIndependente: "Inside",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2016 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Overwatch, Uncharted 4: A Thief's End, DOOM, Inside, Nolan North, 2016",
    },
    {
        Ano: "2017",
        JogodoAno: "The Legend of Zelda: Breath of the Wild",
        MelhorDireção: "The Legend of Zelda: Breath of the Wild",
        MelhorNarrativa: "The Legend of Zelda: Breath of the Wild",
        MelhorAtuação: "Spike VGA 2017 não possui uma categoria específica para Melhor Atuação",
        MelhorTrilhaSonora: "Nier: Automata",
        MelhorDesigndeaudio: "Hellblade: Senua's Sacrifice",
        MelhorDesigndeJogo: "The Legend of Zelda: Breath of the Wild",
        MelhorJogoIndependente: "Cuphead",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2017 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "The Legend of Zelda: Breath of the Wild, Nier: Automata, Hellblade: Senua's Sacrifice, Cuphead, 2017",
    },
    {
        Ano: "2018",
        JogodoAno: "God of War",
        MelhorDireção: "God of War",
        MelhorNarrativa: "God of War",
        MelhorAtuação: "Christopher Judge como Kratos em God of War",
        MelhorTrilhaSonora: "God of War",
        MelhorDesigndeaudio: "God of War",
        MelhorDesigndeJogo: "God of War",
        MelhorJogoIndependente: "Celeste",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2018 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "God of War, Celeste, Christopher Judge, 2018",
    },
    {
        Ano: "2019",
        JogodoAno: "Sekiro: Shadows Die Twice",
        MelhorDireção: "Sekiro: Shadows Die Twice",
        MelhorNarrativa: "Sekiro: Shadows Die Twice",
        MelhorAtuação: "Spike VGA 2019 não possui uma categoria específica para Melhor Atuação",
        MelhorTrilhaSonora: "Death Stranding",
        MelhorDesigndeaudio: "Death Stranding",
        MelhorDesigndeJogo: "Sekiro: Shadows Die Twice",
        MelhorJogoIndependente: "Hades",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2019 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Sekiro: Shadows Die Twice, Death Stranding, Hades, 2019",
    },
    {
        Ano: "2020",
        JogodoAno: "The Last of Us Part II",
        MelhorDireção: "The Last of Us Part II",
        MelhorNarrativa: "The Last of Us Part II",
        MelhorAtuação: "Laura Bailey como Abby em The Last of Us Part II",
        MelhorTrilhaSonora: "Final Fantasy VII Remake",
        MelhorDesigndeaudio: "The Last of Us Part II",
        MelhorDesigndeJogo: "The Last of Us Part II",
        MelhorJogoIndependente: "Hades",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2020 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "The Last of Us Part II, Final Fantasy VII Remake, Hades, Laura Bailey, 2020",
    },
    {
        Ano: "2021",
        JogodoAno: "It Takes Two",
        MelhorDireção: "It Takes Two",
        MelhorNarrativa: "It Takes Two",
        MelhorAtuação: "Spike VGA 2021 não possui uma categoria específica para Melhor Atuação",
        MelhorTrilhaSonora: "It Takes Two",
        MelhorDesigndeaudio: "Deathloop",
        MelhorDesigndeJogo: "It Takes Two",
        MelhorJogoIndependente: "Kena: Bridge of Spirits",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2021 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "It Takes Two, Deathloop, Kena: Bridge of Spirits, 2021",
    },
    {
        Ano: "2022",
        JogodoAno: "Elden Ring",
        MelhorDireção: "Elden Ring",
        MelhorNarrativa: "Elden Ring",
        MelhorAtuação: "Spike VGA 2022 não possui uma categoria específica para Melhor Atuação",
        MelhorTrilhaSonora: "God of War Ragnarök",
        MelhorDesigndeaudio: "God of War Ragnarök",
        MelhorDesigndeJogo: "Elden Ring",
        MelhorJogoIndependente: "Stray",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2022 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Elden Ring, God of War Ragnarök, Stray, 2022",
    },
    {
        Ano: "2023",
        JogodoAno: "Baldur's Gate 3",
        MelhorDireção: "Baldur's Gate 3",
        MelhorNarrativa: "Baldur's Gate 3",
        MelhorAtuação: "Spike VGA 2023 não possui uma categoria específica para Melhor Atuação",
        MelhorTrilhaSonora: "Final Fantasy XVI",
        MelhorDesigndeaudio: "Final Fantasy XVI",
        MelhorDesigndeJogo: "Baldur's Gate 3",
        MelhorJogoIndependente: "Baldur's Gate 3",
        MelhorJogodeRealidadeVirtual: "Spike VGA 2023 não possui uma categoria específica para Melhor Jogo de Realidade Virtual",
        tag: "Baldur's Gate 3, Final Fantasy XVI, 2023",
    }
];
